Develop
IgorAtafev/java-filmorate pull request #20
Opened 2023-04-03 13:38 UTC by IgorAtafev

2023-04-04 14:41 UTC, kalitva requested changes

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDBStorage.java
> +        String sql = "SELECT COUNT(*) FROM director WHERE director_id = ?";
Лучше `SELECT COUNT(1) FROM...`

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventDbStorage.java
> +        long eventId = Objects.requireNonNull(holder.getKey()).longValue();
1. Если не ошибаюсь, чтобы вернулся сгенеренный айди нужно в `prepareStatement` передать аргумент `Statement.RETURN_GENERATED_KEYS`
2. `Objects#requireNonNull` выбрасывает исключение если аргумент null. Это точно то, что нам нужно?

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventDbStorage.java
> +        if (eventId == 0) {
Сгенеренный айди не может быть 0

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
>      private final GenreStorage genreStorage;
Видимо, не заметил в прошлом ревью - стораджи нельзя вайрить друг в друга, они к друг другу обращаться не могут (в сервисы же можно вайрить любые стораджи и другие сервисы)

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (reviewStorage.reviewFilmExists(id)) {
Нам точно нужна эта проверка?

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            reviewsId.forEach(reviewStorage::removeReviewById);
Это необходимо делать одни sql запросом

https://www.baeldung.com/spring-jdbctemplate-in-list

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.addGenres(genreStorage.getGenresByFilmId(film.getId()));
Лучше достать фильм и жанры в сервисе, и засетить жанры в фильм там (`genreStorage` нужно удалить, замечание выше)

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.addDirectors(directorStorage.getDirectorsByFilmId(film.getId()));
То же насчет режиссеров

2023-04-04 14:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    private String setUsefulOperationForAddLike(boolean isUseful) {
`setUsefulOperationForAddLike --> getUsefulOperationForAddLike`

Если метод возвращает значение, он не должен начинаться с `set`

2023-04-04 18:53 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmsForDirector(
Переименовала

2023-04-04 18:53 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public Map<String, Object> toMap() {
Перенесла

2023-04-04 18:53 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorServiceImpl.java
> +    private static final String DIRECTOR_DOSE_NOT_EXIST = "Director with id %d  does not exist";
Поправила

2023-04-04 18:54 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDBStorage.java
> +            return getDirectorById(directorId);
Поправила

2023-04-04 18:54 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDBStorage.java
> +        } catch (Exception ex) {
Поправила

2023-04-04 18:54 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDBStorage.java
> +    }
Поправила

2023-04-04 18:54 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDBStorage.java
> +                "SELECT d.* \n" +
Поправила

2023-04-04 18:54 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDBStorage.java
> +        String sql = "SELECT COUNT(*) FROM director WHERE director_id = ?";
Поправила

2023-04-04 18:57 UTC, catarena-s commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.addDirectors(directorStorage.getDirectorsByFilmId(film.getId()));
Перенесла добавление режиссёров в сервис

2023-04-04 22:41 UTC, valentin32k commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +@Value
Исправил

2023-04-04 22:54 UTC, valentin32k commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +@Value
Исправил

2023-04-04 22:55 UTC, valentin32k commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +                .operation("ADD")
Сделал

2023-04-04 22:56 UTC, valentin32k commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventDbStorage.java
> +        long eventId = Objects.requireNonNull(holder.getKey()).longValue();
Исправил

2023-04-04 22:56 UTC, valentin32k commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventDbStorage.java
> +        if (eventId == 0) {
Исправил

2023-04-05 11:41 UTC, IgorAtafev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        service.removeLike(id, userId, true);
Исправил

2023-04-05 11:42 UTC, IgorAtafev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
>      private final GenreStorage genreStorage;
исправил

2023-04-05 11:44 UTC, IgorAtafev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.addGenres(genreStorage.getGenresByFilmId(film.getId()));
Исправил

2023-04-05 15:31 UTC, OlgaMordvinkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (reviewStorage.reviewFilmExists(id)) {
Убрала

2023-04-05 15:31 UTC, OlgaMordvinkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            reviewsId.forEach(reviewStorage::removeReviewById);
Исправила

2023-04-06 18:20 UTC, kalitva approved these changes

2023-04-06 18:20 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    void addDirectorsToFilms(List<Film> films);
Здесь необходимо принимать список айдишников фильмов, а не список фильмов

2023-04-06 21:09 UTC, catarena-s approved these changes

2023-04-06 21:10 UTC, merged

2023-04-06 21:10 UTC, OlgaMordvinkina approved these changes